#!/usr/bin/env python3
"""Generate a lesson-style PDF with Arabic (vocalized) + English support.
Usage: python3 make_pdf.py input.json output.pdf
JSON: { title, subtitle?, footer?, sections: [ { heading?, body } ] }
Body: paragraphs separated by newlines; Arabic paragraphs are shaped (bidi) and right-aligned.
"""
import json, sys, os
import arabic_reshaper
from bidi.algorithm import get_display
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

DARK = HexColor('#0E2A2B'); GOLD = HexColor('#C9A96A'); TEXT = HexColor('#1a1a1a')

def register_fonts():
    f = {}
    for name, path, fallback in [
        ('en', '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf', 'Helvetica'),
        ('enb', '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf', 'Helvetica-Bold'),
        ('ar', os.path.join(os.path.dirname(__file__), '..', 'fonts', 'NotoNaskhArabic-Regular.ttf'), None),
    ]:
        try:
            pdfmetrics.registerFont(TTFont(name, path)); f[name] = name
        except Exception:
            f[name] = fallback
    return f

FONTS = register_fonts()

def is_arabic(s):
    return any('\u0600' <= c <= '\u06FF' or '\u0750' <= c <= '\u077F' or '\uFB50' <= c <= '\uFEFF' for c in s)

def shape(t):
    return get_display(arabic_reshaper.reshape(t))

def wrap(c, text, font, size, maxw):
    words = text.split(' ')
    lines, cur = [], ''
    for w in words:
        t = (cur + ' ' + w).strip()
        if c.stringWidth(t, font, size) > maxw and cur:
            lines.append(cur); cur = w
        else:
            cur = t
    if cur: lines.append(cur)
    return lines


def draw_footer(c, text, page_no):
    W, H = A4
    c.setFont(FONTS['en'], 8); c.setFillColor(HexColor('#888888'))
    c.drawCentredString(W / 2, 12 * mm, text + '  ·  page ' + str(page_no))

def main(inp, outp):
    global FOOT
    spec = json.load(open(inp, encoding='utf-8'))
    FOOT = spec.get('footer', 'Generated by Studio API')
    W, H = A4
    M = 22 * mm
    maxw = W - 2 * M
    c = canvas.Canvas(outp, pagesize=A4)
    c.setTitle(spec.get('title', 'Lesson'))
    y = H - M
    # header band
    c.setFillColor(DARK); c.rect(0, H - 30 * mm, W, 30 * mm, stroke=0, fill=1)
    c.setFillColor(HexColor('#F3ECDA')); c.setFont(FONTS['enb'], 18)
    c.drawCentredString(W / 2, H - 15 * mm, spec.get('title', 'Lesson'))
    if spec.get('subtitle'):
        c.setFont(FONTS['en'], 10); c.setFillColor(GOLD)
        c.drawCentredString(W / 2, H - 23 * mm, spec['subtitle'])
    y = H - 40 * mm
    for si, sec in enumerate(spec.get('sections', [])):
        if sec.get('heading'):
            if y < M + 30 * mm:
                draw_footer(c, FOOT, c.getPageNumber()); c.showPage(); y = H - M
            c.setFillColor(GOLD); c.setFont(FONTS['enb'], 13)
            c.drawString(M, y, sec['heading'])
            c.setStrokeColor(GOLD); c.setLineWidth(1)
            c.line(M, y - 2 * mm, W - M, y - 2 * mm)
            y -= 9 * mm
        body = str(sec.get('body', '')).strip()
        if not body: continue
        for para in [p for p in body.split('\n') if p.strip()]:
            ar = is_arabic(para)
            font = FONTS['ar'] if ar and FONTS.get('ar') else FONTS['en']
            size = 16 if ar else 11
            lead = size * 1.6
            text = shape(para) if ar else para
            for ln in wrap(c, text, font, size, maxw):
                if y < M + 5 * mm:
                    draw_footer(c, FOOT, c.getPageNumber()); c.showPage(); y = H - M
                c.setFillColor(TEXT); c.setFont(font, size)
                if ar:
                    c.drawRightString(W - M, y, ln)
                else:
                    c.drawString(M, y, ln)
                y -= lead
            y -= 4 * mm
        y -= 3 * mm
    # footer on the last page
    draw_footer(c, spec.get('footer', 'Generated by Studio API'), c.getPageNumber())
    c.save()

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
